### ISSUE TITLE
Deprecated Libraries being used.

### ISSUE THREAD

**Issue by saiksaif** [racmathafidz/racxstudio#1]
A lot of libraries being used are deprecated. 

They can still be installed using ```npm i --legacy-peer-deps```. 

Even after installing them when I try to start server I get error: 

"Error: error:0308010C:digital envelope routines::unsupported    
 at new Hash (node:internal/crypto/hash:69:19)".

**Comment by santoshjammi** [comment]
This is still the problem, any updates??

**Comment by racmathafidz** [comment]
Hello, sorry for my late response.
Actually, Racxstudio is my old project.
So if you want to run it you have to change your current nodejs version to 12.22.12.
Then run `'npm install'` and `'npm start'`.
Good luck!
@saiksaif  @santoshjammi
